### ISSUE TITLE
Error creating symbolic link

### ISSUE THREAD

**Issue by praran26** [chrishantha/install-java#1]
**install-java.sh:152**

`sudo update-alternatives --install "/usr/lib/mozilla/plugins/libjavaplugin.so" "mozilla-javaplugin.so" "$extracted_dirname/jre/lib/amd64/libnpjp2.so" 1`

This command gave me following error on Ubuntu 16.04 64-bit:

`update-alternatives: error: error creating symbolic link '/usr/lib/mozilla/plugins/libjavaplugin.so.dpkg-tmp': No such file or directory`

Possible fix that worked for me is replacing `/usr/lib/mozilla/plugins/libjavaplugin.so.dpkg-tmp` to `/usr/lib/firefox-addons/plugins/libjavaplugin.so.dpkg-tmp`.

**Comment by chrishantha** [comment]
I also have Ubuntu 16.04 64-bit and I don't have any issue with running Java in Firefox. I have Firefox 48.

**Comment by chrishantha** [comment]
Hi @praran26, I also faced the same issue when I try to install Java on Ubuntu 16.04.2 LTS Server. I will check how we can fix this issue.

**Comment by praran26** [comment]
Accept the pull request and it'll work. @chrishantha

**Comment by chrishantha** [comment]
Hi, I faced error as there is no plugins directory in Ubuntu server version. So, I didn't accept your pull request.

Thanks!
