### ISSUE TITLE
Does it works for JDK8 i586?

### ISSUE THREAD

**Issue by jbagatella** [chrishantha/install-java#5]
Hello.
I want to use your script with the jdk-8u181-linux-i586.tar.gz and the execution of:

# ./install-java.sh -f jdk-8u181-linux-i586.tar.gz

Returns:
Please specify a valid java distribution

Both files are in the same directory.

Also I've checked your code and I can't see support for jdk8
Regards.

**Comment by chrishantha** [comment]
Hello,

I actually haven't tested `jdk-8u181-linux-i586.tar.gz` or any previous distributions with `*i586.tar.gz`

I will update the regex at line: https://github.com/chrishantha/install-java/blob/8edab72b630eed83e3eeda7dff2195c7cfd6083d/install-java.sh#L96

It seems I have never used 32-bit version of JDK. :( Please give me some time to update.

In the mean time, will you be able to change the regex and see?

Changing the line as follows should work.

    java_78_dist_file_regex="jdk-([78])u([0-9]{1,3})-linux-(i586|x64)\.tar\.gz"

**Comment by chrishantha** [comment]
Hello @jbagatella, Could you please try the updated script? Thank you.
