### ISSUE TITLE
Issues with OpenJDK 12

### ISSUE THREAD

**Issue by boktai1000** [chrishantha/install-java#6]
Just tried using the install-java.sh script on OpenJDK 12, filename: **openjdk-12.0.1_linux-x64_bin.tar.gz**

I'm using CentOS 7.6, but I can't imagine it's a problem with CentOS because there's nothing different or unique about the Distro that should be tripping it up at this part of the script I would think (like any sort of apt-get or distro specific commands). Also the Unzip package is installed, but I don't think that's the issue.

```
[root@testing-centos-03 ~]# yes | ./install-java.sh -f openjdk-12.0.1_linux-x64_bin.tar.gz
Extracting openjdk-12.0.1_linux-x64_bin.tar.gz to /usr/lib/jvm
JDK is extracted to /usr/lib/jvm/openjdk-12.0.1
Couldn't check the extracted directory. Please check the installation script
[root@testing-centos-03 ~]#
```

Looking at the code, I think the filename / extracted directory may be tripping up the script, possibly due to changing naming conventions with OpenJDK 12 (and maybe 11?) Just my best guess without fully picking things apart.

```
if [[ $java_dist_filename =~ $java_78_dist_file_regex ]]; then
    jdk_dir=$(echo $java_dist_filename | sed -nE "s/$java_78_dist_file_regex/jdk1.\1.0_\2/p")
    jdk_major_version=$(echo $jdk_dir | sed -nE 's/jdk1\.([0-9]*).*/\1/p')
elif [[ $java_dist_filename =~ $java_9up_dist_file_regex ]]; then
    jdk_dir=$(echo $java_dist_filename | sed -nE "s/$java_9up_dist_file_regex/jdk-\1/p")
    jdk_major_version=$(echo $jdk_dir | sed -nE 's/jdk-([0-9]*).*/\1/p')
else
    echo "Please specify a valid java distribution"
    exit 1
fi

extracted_dirname=$java_dir"/"$jdk_dir

# Extract Java Distribution

if [[ ! -d $extracted_dirname ]]; then
    echo "Extracting $java_dist to $java_dir"
    tar -xof $java_dist -C $java_dir
    echo "JDK is extracted to $extracted_dirname"
else 
    echo "JDK is already extracted to $extracted_dirname"
fi


if [[ ! -f $extracted_dirname"/bin/java" ]]; then
    echo "Couldn't check the extracted directory. Please check the installation script"
    exit 1
fi
```

I'm not entirely sure, but thought I'd post here to let you know! I didn't see any mentions of OpenJDK 11 or 12, so maybe I shouldn't assume that it's supported - unfortunately there seem to be articles going around that are linking to your tool saying that it will install "any JDK version" which is how I came across it https://www.linuxuprising.com/2019/02/install-any-oracle-java-jdk-version-in.html

**Comment by chrishantha** [comment]
Thanks for telling me that my script is mentioned in https://www.linuxuprising.com. It's a surprise for me :)

However, as I mentioned in README, the script only installs "Oracle" JDK versions. It does not support OpenJDK. I wrote these scripts as there was no installation script to setup Oracle JDK on Linux. I frequently update Oracle JDK version and this script was really helpful for me to setup Oracle JDK within few seconds!

**Comment by boktai1000** [comment]
Gotcha! Appreciate the clarification :)

**Comment by chrishantha** [comment]
@boktai1000 I did some minor modifications to support OpenJDK now. If possible, please check the latest script.

**Comment by boktai1000** [comment]
@chrishantha I just tried it, and it worked! Thank you. If you have a second for a quick question post install, I was wondering two things.

1. What is the "Java System Prefs Directory"? `"Create Java System Prefs Directory and change ownership"`

2. Where is the JAVA_HOME environment variable being set? `Do you want to set JAVA_HOME environment variable?` I replied `y` to this, but an `echo $JAVA_HOME` returns nothing.

Thanks!

Update: In response to 2) it seems that relaunching my shell has the variable set properly now, it just seems like the script is not sourcing or setting for current running user from the script, instead waiting for the user to open a new shell/etc. Still curious about where that is set though so appreciate it :)

**Comment by chrishantha** [comment]
@boktai1000 Thank you very much for trying the script!

1. I create the directory `/etc/.java/.systemPrefs` and change ownership to current user.  https://github.com/chrishantha/install-java/blob/2348c1589aa53b982d043b3dfe58ee81232a2a34/install-java.sh#L193 Without that directory, I have seen Java warnings. For example, see https://stackoverflow.com/questions/23960451/java-system-preferences-under-different-users-in-linux

2. `JAVA_HOME` environment variable is set in `$HOME/.bashrc`. After that I source it as well.  https://github.com/chrishantha/install-java/blob/2348c1589aa53b982d043b3dfe58ee81232a2a34/install-java.sh#L203-L208 I believe that `bash` is the default shell in your CentOS. Do you have `$HOME/.bashrc` file?

**Comment by chrishantha** [comment]
I also added support for AdoptOpenJDK. Please create a new issue if you find any problems with the script. Thank you.
